GET http://localhost:3000/products


###

POST http://localhost:3000/products
Content-Type: application/json

{
  
 "name": "Gabriel Portilho",
 "price": 1.99,
 "description": "Representante soberano supremo",
 "category": "Águia"

}

###

DELETE http://localhost:3000/products/:42